server:
  port: 8888
  servlet:
    context-path: ''

logging:
  file:
    name: '/var/log/${spring.application.name}.log'

eureka:
  instance:
    hostname: ${HOSTNAME}
    preferIpAddress: true
    instanceId: '${eureka.instance.hostname}:${server.port}'
    homePageUrl: 'http://${eureka.instance.hostname}:${server.port}'
    healthCheckUrl: 'http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/actuator/health'
    metadataMap:
      management:
        context-path: ${server.servlet.context-path}/actuator
        port: ${server.port}

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: 'http://eureka:8761/eureka'
