application:
  name: config-server
spring:
  application:
    name: ${application.name}
  cloud:
    config:
      server:
        git:
          search-paths: '{application}'
          uri: 'https://github.com/amoraes/spring-cloud-ecs-example-config.git'
          default-label: master
          clone-on-start: true

server:
  port: 8888